// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwlw0tBCBPA9kf-2nxZFKJ8Ljf6bk9SqM',
    appId: '1:815542967882:web:ef41db99f2cd39cc02d0b3',
    messagingSenderId: '815542967882',
    projectId: 'defogging-e4c51',
    authDomain: 'defogging-e4c51.firebaseapp.com',
    storageBucket: 'defogging-e4c51.firebasestorage.app',
    measurementId: 'G-C36F18VFQF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBt7qlZUlITVabFC5_-V-EFbkfePaBtT6g',
    appId: '1:815542967882:android:928e29f05343030402d0b3',
    messagingSenderId: '815542967882',
    projectId: 'defogging-e4c51',
    storageBucket: 'defogging-e4c51.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2Rm_6TvJ0GOSKdbBp5O1rpKX5Gc3O-dk',
    appId: '1:815542967882:ios:eab7b274410a035b02d0b3',
    messagingSenderId: '815542967882',
    projectId: 'defogging-e4c51',
    storageBucket: 'defogging-e4c51.firebasestorage.app',
    iosBundleId: 'com.example.defoggingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2Rm_6TvJ0GOSKdbBp5O1rpKX5Gc3O-dk',
    appId: '1:815542967882:ios:eab7b274410a035b02d0b3',
    messagingSenderId: '815542967882',
    projectId: 'defogging-e4c51',
    storageBucket: 'defogging-e4c51.firebasestorage.app',
    iosBundleId: 'com.example.defoggingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDwlw0tBCBPA9kf-2nxZFKJ8Ljf6bk9SqM',
    appId: '1:815542967882:web:eb86324bd05fd93502d0b3',
    messagingSenderId: '815542967882',
    projectId: 'defogging-e4c51',
    authDomain: 'defogging-e4c51.firebaseapp.com',
    storageBucket: 'defogging-e4c51.firebasestorage.app',
    measurementId: 'G-RQN1FZ6778',
  );
}
